// GENERADO AUTOMÁTICAMENTE — no editar a mano.
// Regenerar contra el proyecto alojado:
//   npm run db:types

export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];

export type Enums = {
  bay_status: "disponible" | "ocupada" | "mantenimiento" | "limpieza";
  bay_type: "prelavado" | "lavado" | "aspirado" | "secado" | "detallado" | "qc";
  benefit_status: "validado" | "reservado" | "en_proceso" | "consumido" | "cancelado";
  cash_movement_type: "inflow" | "outflow";
  cash_session_status: "open" | "closed";
  expense_category: "quimicos_insumos" | "servicios_publicos" | "mantenimiento_equipos" | "nomina_extras" | "varios";
  fuel_level: "reserva" | "1/4" | "1/2" | "3/4" | "lleno";
  item_type: "service" | "package" | "product";
  membego_status: "active" | "inactive" | "none";
  ncf_type: "B01" | "B02" | "B04" | "B14" | "B15";
  order_status: "pendiente" | "en_espera" | "asignada" | "en_proceso" | "control_calidad" | "listo" | "entregado" | "cancelado";
  payment_method: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
  payment_status: "pendiente" | "pagado" | "parcial" | "reembolsado";
  printer_width: "58mm" | "80mm" | "letter";
  user_role: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin";
  vehicle_category: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
};

export interface Database {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: number;
          company_id: string;
          branch_id: string | null;
          actor_id: string | null;
          actor_name: string;
          actor_role: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          action: string;
          entity: string;
          entity_id: string | null;
          details: string;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          occurred_at: string;
        };
        Insert: {
          id?: number;
          company_id: string;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_name?: string;
          actor_role?: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          action: string;
          entity: string;
          entity_id?: string | null;
          details?: string;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          occurred_at?: string;
        };
        Update: {
          id?: number;
          company_id?: string;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_name?: string;
          actor_role?: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          action?: string;
          entity?: string;
          entity_id?: string | null;
          details?: string;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          occurred_at?: string;
        };
      };
      bays: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          name: string;
          type: "prelavado" | "lavado" | "aspirado" | "secado" | "detallado" | "qc";
          status: "disponible" | "ocupada" | "mantenimiento" | "limpieza";
          current_work_order_id: string | null;
          assigned_profile_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          name: string;
          type?: "prelavado" | "lavado" | "aspirado" | "secado" | "detallado" | "qc";
          status?: "disponible" | "ocupada" | "mantenimiento" | "limpieza";
          current_work_order_id?: string | null;
          assigned_profile_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          name?: string;
          type?: "prelavado" | "lavado" | "aspirado" | "secado" | "detallado" | "qc";
          status?: "disponible" | "ocupada" | "mantenimiento" | "limpieza";
          current_work_order_id?: string | null;
          assigned_profile_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      branches: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          address: string | null;
          phone: string | null;
          is_main: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          address?: string | null;
          phone?: string | null;
          is_main?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          address?: string | null;
          phone?: string | null;
          is_main?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      cash_movements: {
        Row: {
          id: string;
          company_id: string;
          cash_session_id: string;
          type: "inflow" | "outflow";
          method: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          amount_cents: number;
          reason: string;
          invoice_id: string | null;
          expense_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          cash_session_id: string;
          type: "inflow" | "outflow";
          method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          amount_cents: number;
          reason: string;
          invoice_id?: string | null;
          expense_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          cash_session_id?: string;
          type?: "inflow" | "outflow";
          method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          amount_cents?: number;
          reason?: string;
          invoice_id?: string | null;
          expense_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      cash_sessions: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          cashier_id: string;
          opened_at: string;
          closed_at: string | null;
          initial_amount_cents: number;
          total_cash_sales_cents: number;
          total_card_sales_cents: number;
          total_transfer_sales_cents: number;
          total_membego_cents: number;
          total_inflows_cents: number;
          total_outflows_cents: number;
          expected_cash_cents: number;
          counted_cash_cents: number | null;
          difference_cents: number | null;
          status: "open" | "closed";
          opening_notes: string | null;
          closing_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          cashier_id: string;
          opened_at?: string;
          closed_at?: string | null;
          initial_amount_cents: number;
          total_cash_sales_cents?: number;
          total_card_sales_cents?: number;
          total_transfer_sales_cents?: number;
          total_membego_cents?: number;
          total_inflows_cents?: number;
          total_outflows_cents?: number;
          expected_cash_cents?: number;
          counted_cash_cents?: number | null;
          difference_cents?: number | null;
          status?: "open" | "closed";
          opening_notes?: string | null;
          closing_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          cashier_id?: string;
          opened_at?: string;
          closed_at?: string | null;
          initial_amount_cents?: number;
          total_cash_sales_cents?: number;
          total_card_sales_cents?: number;
          total_transfer_sales_cents?: number;
          total_membego_cents?: number;
          total_inflows_cents?: number;
          total_outflows_cents?: number;
          expected_cash_cents?: number;
          counted_cash_cents?: number | null;
          difference_cents?: number | null;
          status?: "open" | "closed";
          opening_notes?: string | null;
          closing_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      commissions: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          profile_id: string;
          work_order_id: string;
          work_order_item_id: string | null;
          service_name: string;
          base_cents: number;
          commission_bps: number;
          amount_cents: number;
          earned_on: string;
          is_paid: boolean;
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          profile_id: string;
          work_order_id: string;
          work_order_item_id?: string | null;
          service_name: string;
          base_cents: number;
          commission_bps: number;
          amount_cents: number;
          earned_on?: string;
          is_paid?: boolean;
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          profile_id?: string;
          work_order_id?: string;
          work_order_item_id?: string | null;
          service_name?: string;
          base_cents?: number;
          commission_bps?: number;
          amount_cents?: number;
          earned_on?: string;
          is_paid?: boolean;
          paid_at?: string | null;
          created_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          trade_name: string;
          legal_name: string;
          tax_id: string;
          logo_url: string | null;
          currency: string;
          currency_symbol: string;
          timezone: string;
          tax_rate_bps: number;
          allow_guest_checkout: boolean;
          thermal_printer_width: "58mm" | "80mm" | "letter";
          header_note: string | null;
          footer_note: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trade_name: string;
          legal_name: string;
          tax_id: string;
          logo_url?: string | null;
          currency?: string;
          currency_symbol?: string;
          timezone?: string;
          tax_rate_bps?: number;
          allow_guest_checkout?: boolean;
          thermal_printer_width?: "58mm" | "80mm" | "letter";
          header_note?: string | null;
          footer_note?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trade_name?: string;
          legal_name?: string;
          tax_id?: string;
          logo_url?: string | null;
          currency?: string;
          currency_symbol?: string;
          timezone?: string;
          tax_rate_bps?: number;
          allow_guest_checkout?: boolean;
          thermal_printer_width?: "58mm" | "80mm" | "letter";
          header_note?: string | null;
          footer_note?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          name: string;
          phone: string | null;
          email: string | null;
          tax_id: string | null;
          address: string | null;
          notes: string | null;
          is_anonymous_guest: boolean;
          membego_customer_id: string | null;
          membego_status: "active" | "inactive" | "none";
          membego_tier: string | null;
          total_visits: number;
          total_spent_cents: number;
          last_visit_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          name: string;
          phone?: string | null;
          email?: string | null;
          tax_id?: string | null;
          address?: string | null;
          notes?: string | null;
          is_anonymous_guest?: boolean;
          membego_customer_id?: string | null;
          membego_status?: "active" | "inactive" | "none";
          membego_tier?: string | null;
          total_visits?: number;
          total_spent_cents?: number;
          last_visit_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          name?: string;
          phone?: string | null;
          email?: string | null;
          tax_id?: string | null;
          address?: string | null;
          notes?: string | null;
          is_anonymous_guest?: boolean;
          membego_customer_id?: string | null;
          membego_status?: "active" | "inactive" | "none";
          membego_tier?: string | null;
          total_visits?: number;
          total_spent_cents?: number;
          last_visit_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      document_counters: {
        Row: {
          company_id: string;
          scope: string;
          period: string;
          next_value: number;
        };
        Insert: {
          company_id: string;
          scope: string;
          period?: string;
          next_value?: number;
        };
        Update: {
          company_id?: string;
          scope?: string;
          period?: string;
          next_value?: number;
        };
      };
      expenses: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          category: "quimicos_insumos" | "servicios_publicos" | "mantenimiento_equipos" | "nomina_extras" | "varios";
          description: string;
          amount_cents: number;
          payment_method: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          supplier_name: string | null;
          invoice_ref: string | null;
          cash_session_id: string | null;
          expense_date: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          category?: "quimicos_insumos" | "servicios_publicos" | "mantenimiento_equipos" | "nomina_extras" | "varios";
          description: string;
          amount_cents: number;
          payment_method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          supplier_name?: string | null;
          invoice_ref?: string | null;
          cash_session_id?: string | null;
          expense_date?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          category?: "quimicos_insumos" | "servicios_publicos" | "mantenimiento_equipos" | "nomina_extras" | "varios";
          description?: string;
          amount_cents?: number;
          payment_method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto";
          supplier_name?: string | null;
          invoice_ref?: string | null;
          cash_session_id?: string | null;
          expense_date?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          item_type: "service" | "package" | "product";
          service_id: string | null;
          product_id: string | null;
          name: string;
          quantity: number;
          unit_price_cents: number;
          discount_cents: number;
          is_membego_covered: boolean;
          created_at: string;
          company_id: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          item_type: "service" | "package" | "product";
          service_id?: string | null;
          product_id?: string | null;
          name: string;
          quantity: number;
          unit_price_cents: number;
          discount_cents?: number;
          is_membego_covered?: boolean;
          created_at?: string;
          company_id: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          item_type?: "service" | "package" | "product";
          service_id?: string | null;
          product_id?: string | null;
          name?: string;
          quantity?: number;
          unit_price_cents?: number;
          discount_cents?: number;
          is_membego_covered?: boolean;
          created_at?: string;
          company_id?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          invoice_number: string;
          ncf: string | null;
          ncf_type: "B01" | "B02" | "B04" | "B14" | "B15" | null;
          work_order_id: string | null;
          customer_id: string | null;
          customer_name: string;
          customer_tax_id: string | null;
          vehicle_plate: string | null;
          subtotal_cents: number;
          discount_cents: number;
          tax_cents: number;
          total_cents: number;
          change_cents: number;
          cash_session_id: string | null;
          cashier_id: string;
          is_annulled: boolean;
          annulled_reason: string | null;
          annulled_at: string | null;
          annulled_by: string | null;
          credit_note_id: string | null;
          created_at: string;
          updated_at: string;
          client_request_id: string | null;
          credits_invoice_id: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          invoice_number: string;
          ncf?: string | null;
          ncf_type?: "B01" | "B02" | "B04" | "B14" | "B15" | null;
          work_order_id?: string | null;
          customer_id?: string | null;
          customer_name: string;
          customer_tax_id?: string | null;
          vehicle_plate?: string | null;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          change_cents?: number;
          cash_session_id?: string | null;
          cashier_id: string;
          is_annulled?: boolean;
          annulled_reason?: string | null;
          annulled_at?: string | null;
          annulled_by?: string | null;
          credit_note_id?: string | null;
          created_at?: string;
          updated_at?: string;
          client_request_id?: string | null;
          credits_invoice_id?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          invoice_number?: string;
          ncf?: string | null;
          ncf_type?: "B01" | "B02" | "B04" | "B14" | "B15" | null;
          work_order_id?: string | null;
          customer_id?: string | null;
          customer_name?: string;
          customer_tax_id?: string | null;
          vehicle_plate?: string | null;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          change_cents?: number;
          cash_session_id?: string | null;
          cashier_id?: string;
          is_annulled?: boolean;
          annulled_reason?: string | null;
          annulled_at?: string | null;
          annulled_by?: string | null;
          credit_note_id?: string | null;
          created_at?: string;
          updated_at?: string;
          client_request_id?: string | null;
          credits_invoice_id?: string | null;
        };
      };
      ncf_sequences: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          ncf_type: "B01" | "B02" | "B04" | "B14" | "B15";
          series: string;
          range_start: number;
          range_end: number;
          next_value: number;
          authorized_until: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          ncf_type: "B01" | "B02" | "B04" | "B14" | "B15";
          series?: string;
          range_start: number;
          range_end: number;
          next_value: number;
          authorized_until: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          ncf_type?: "B01" | "B02" | "B04" | "B14" | "B15";
          series?: string;
          range_start?: number;
          range_end?: number;
          next_value?: number;
          authorized_until?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          code: string;
          barcode: string | null;
          name: string;
          category: string;
          cost_cents: number;
          price_cents: number;
          stock: number;
          min_stock: number;
          unit: string;
          is_for_sale: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          code: string;
          barcode?: string | null;
          name: string;
          category?: string;
          cost_cents?: number;
          price_cents?: number;
          stock?: number;
          min_stock?: number;
          unit?: string;
          is_for_sale?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          code?: string;
          barcode?: string | null;
          name?: string;
          category?: string;
          cost_cents?: number;
          price_cents?: number;
          stock?: number;
          min_stock?: number;
          unit?: string;
          is_for_sale?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          company_id: string | null;
          branch_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          role: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          avatar_url: string | null;
          cash_pin_hash: string | null;
          commission_bps: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          company_id?: string | null;
          branch_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          role?: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          avatar_url?: string | null;
          cash_pin_hash?: string | null;
          commission_bps?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string | null;
          branch_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          role?: "propietario" | "administrador" | "supervisor" | "cajero" | "recepcionista" | "operario" | "contador" | "superadmin" | null;
          avatar_url?: string | null;
          cash_pin_hash?: string | null;
          commission_bps?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_prices: {
        Row: {
          service_id: string;
          vehicle_category: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          price_cents: number;
        };
        Insert: {
          service_id: string;
          vehicle_category: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          price_cents: number;
        };
        Update: {
          service_id?: string;
          vehicle_category?: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          price_cents?: number;
        };
      };
      services: {
        Row: {
          id: string;
          company_id: string;
          code: string;
          name: string;
          description: string;
          category: string;
          estimated_minutes: number;
          commission_bps: number;
          requires_inspection: boolean;
          included_in_membego: boolean;
          is_popular: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          code: string;
          name: string;
          description?: string;
          category?: string;
          estimated_minutes?: number;
          commission_bps?: number;
          requires_inspection?: boolean;
          included_in_membego?: boolean;
          is_popular?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          code?: string;
          name?: string;
          description?: string;
          category?: string;
          estimated_minutes?: number;
          commission_bps?: number;
          requires_inspection?: boolean;
          included_in_membego?: boolean;
          is_popular?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          company_id: string;
          customer_id: string | null;
          plate: string;
          make: string;
          model: string;
          year: number | null;
          color: string;
          category: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          notes: string | null;
          last_visit_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_id?: string | null;
          plate: string;
          make?: string;
          model?: string;
          year?: number | null;
          color?: string;
          category?: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          notes?: string | null;
          last_visit_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_id?: string | null;
          plate?: string;
          make?: string;
          model?: string;
          year?: number | null;
          color?: string;
          category?: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          notes?: string | null;
          last_visit_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      work_order_items: {
        Row: {
          id: string;
          work_order_id: string;
          item_type: "service" | "package" | "product";
          service_id: string | null;
          product_id: string | null;
          name: string;
          quantity: number;
          unit_price_cents: number;
          discount_cents: number;
          is_membego_covered: boolean;
          assigned_profile_id: string | null;
          created_at: string;
          company_id: string;
        };
        Insert: {
          id?: string;
          work_order_id: string;
          item_type: "service" | "package" | "product";
          service_id?: string | null;
          product_id?: string | null;
          name: string;
          quantity?: number;
          unit_price_cents: number;
          discount_cents?: number;
          is_membego_covered?: boolean;
          assigned_profile_id?: string | null;
          created_at?: string;
          company_id: string;
        };
        Update: {
          id?: string;
          work_order_id?: string;
          item_type?: "service" | "package" | "product";
          service_id?: string | null;
          product_id?: string | null;
          name?: string;
          quantity?: number;
          unit_price_cents?: number;
          discount_cents?: number;
          is_membego_covered?: boolean;
          assigned_profile_id?: string | null;
          created_at?: string;
          company_id?: string;
        };
      };
      work_orders: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string;
          order_number: string;
          customer_id: string | null;
          customer_name: string;
          customer_phone: string | null;
          vehicle_id: string | null;
          vehicle_plate: string;
          vehicle_make_model: string;
          vehicle_category: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          vehicle_color: string;
          status: "pendiente" | "en_espera" | "asignada" | "en_proceso" | "control_calidad" | "listo" | "entregado" | "cancelado";
          priority: string;
          bay_id: string | null;
          subtotal_cents: number;
          discount_cents: number;
          membego_benefit_cents: number;
          tax_cents: number;
          total_cents: number;
          payment_status: "pendiente" | "pagado" | "parcial" | "reembolsado";
          payment_method: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto" | null;
          membego_customer_id: string | null;
          membego_membership_id: string | null;
          membego_benefit_id: string | null;
          membego_redemption_id: string | null;
          benefit_status: "validado" | "reservado" | "en_proceso" | "consumido" | "cancelado" | null;
          arrival_at: string;
          started_at: string | null;
          finished_at: string | null;
          delivered_at: string | null;
          estimated_ready_at: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id: string;
          order_number: string;
          customer_id?: string | null;
          customer_name: string;
          customer_phone?: string | null;
          vehicle_id?: string | null;
          vehicle_plate: string;
          vehicle_make_model?: string;
          vehicle_category?: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          vehicle_color?: string;
          status?: "pendiente" | "en_espera" | "asignada" | "en_proceso" | "control_calidad" | "listo" | "entregado" | "cancelado";
          priority?: string;
          bay_id?: string | null;
          subtotal_cents?: number;
          discount_cents?: number;
          membego_benefit_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          payment_status?: "pendiente" | "pagado" | "parcial" | "reembolsado";
          payment_method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto" | null;
          membego_customer_id?: string | null;
          membego_membership_id?: string | null;
          membego_benefit_id?: string | null;
          membego_redemption_id?: string | null;
          benefit_status?: "validado" | "reservado" | "en_proceso" | "consumido" | "cancelado" | null;
          arrival_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          delivered_at?: string | null;
          estimated_ready_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string;
          order_number?: string;
          customer_id?: string | null;
          customer_name?: string;
          customer_phone?: string | null;
          vehicle_id?: string | null;
          vehicle_plate?: string;
          vehicle_make_model?: string;
          vehicle_category?: "sedan" | "suv" | "jeep" | "pickup" | "van" | "truck" | "motorcycle" | "special";
          vehicle_color?: string;
          status?: "pendiente" | "en_espera" | "asignada" | "en_proceso" | "control_calidad" | "listo" | "entregado" | "cancelado";
          priority?: string;
          bay_id?: string | null;
          subtotal_cents?: number;
          discount_cents?: number;
          membego_benefit_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          payment_status?: "pendiente" | "pagado" | "parcial" | "reembolsado";
          payment_method?: "efectivo" | "tarjeta" | "transferencia" | "pago_movil" | "membego_beneficio" | "credito" | "cortesia" | "mixto" | null;
          membego_customer_id?: string | null;
          membego_membership_id?: string | null;
          membego_benefit_id?: string | null;
          membego_redemption_id?: string | null;
          benefit_status?: "validado" | "reservado" | "en_proceso" | "consumido" | "cancelado" | null;
          arrival_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          delivered_at?: string | null;
          estimated_ready_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertDto<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateDto<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

