-- =============================================================================
-- ¿ME FALTA ALGUNA MIGRACIÓN?  ·  Ejecutar en el editor SQL de Supabase
-- =============================================================================
-- Pegue TODO este archivo y dele «Run». La primera fila del resultado es el
-- veredicto; debajo va el detalle, una fila por migración.
--
-- Por qué existe teniendo ya `estado_migraciones.sql`: aquel busca UN objeto por
-- migración, así que solo sabe si el parche arrancó. Este comprueba los 510
-- objetos que crean las 33 migraciones —tablas, columnas, funciones, tipos,
-- disparadores, políticas e índices— uno por uno. Si un parche se cortó a la
-- mitad, aquí sale «INCOMPLETA» con el nombre de lo que falta; allá salía
-- «aplicada».
--
-- Es seguro y repetible:
--   · No lee ni modifica un solo dato del negocio. Solo consulta el catálogo del
--     sistema (pg_class, pg_proc, pg_policies, information_schema…).
--   · Lo único que escribe es `app.schema_migrations`, el registro de
--     migraciones: sella las completas y le quita el sello a las incompletas,
--     para que el registro no mienta.
--   · Puede ejecutarlo las veces que quiera.
--
-- Cómo leer la columna ESTADO:
--   ✅ aplicada     Están todos sus objetos. No hay nada que hacer.
--   ⚠️ INCOMPLETA   El parche corrió a medias. Vuelva a ejecutarlo ENTERO: todos
--                   los parches son idempotentes, repetirlos no rompe nada.
--   ❌ FALTA        No corrió. Ejecute el parche de la última columna.
--
-- Si algo sale ⚠️ o ❌, ejecute los parches en el orden en que aparecen: cada uno
-- se apoya en el anterior.
-- =============================================================================

create schema if not exists app;

create table if not exists app.schema_migrations (
  version     text primary key,
  name        text not null,
  patch_file  text,
  applied_at  timestamptz not null default now(),
  detected    boolean not null default false
);

-- ---------------------------------------------------------------- El informe
with esperadas (num, modulo, parche, tipo, objeto) as (
  values
    ('0001', 'Cimientos y roles', null, 'type', 'app.user_role'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.vehicle_category'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.order_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.payment_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.payment_method'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.benefit_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.membego_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.bay_type'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.bay_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.item_type'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.expense_category'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.cash_session_status'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.cash_movement_type'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.printer_width'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.fuel_level'),
    ('0001', 'Cimientos y roles', null, 'type', 'app.ncf_type'),
    ('0001', 'Cimientos y roles', null, 'func', 'app.touch_updated_at'),
    ('0002', 'Empresas y perfiles', null, 'table', 'public.companies'),
    ('0002', 'Empresas y perfiles', null, 'table', 'public.branches'),
    ('0002', 'Empresas y perfiles', null, 'table', 'public.profiles'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.check_profile_branch'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.handle_new_auth_user'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.current_company_id'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.current_branch_id'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.current_role'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.has_role'),
    ('0002', 'Empresas y perfiles', null, 'func', 'app.belongs_to_tenant'),
    ('0002', 'Empresas y perfiles', null, 'trigger', 'companies_touch'),
    ('0002', 'Empresas y perfiles', null, 'trigger', 'branches_touch'),
    ('0002', 'Empresas y perfiles', null, 'trigger', 'profiles_touch'),
    ('0002', 'Empresas y perfiles', null, 'trigger', 'profiles_branch_belongs_to_company'),
    ('0002', 'Empresas y perfiles', null, 'trigger', 'on_auth_user_created'),
    ('0002', 'Empresas y perfiles', null, 'index', 'public.branches_company_idx'),
    ('0002', 'Empresas y perfiles', null, 'index', 'public.branches_one_main_per_company'),
    ('0002', 'Empresas y perfiles', null, 'index', 'public.profiles_company_idx'),
    ('0002', 'Empresas y perfiles', null, 'index', 'public.profiles_branch_idx'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.services'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.service_prices'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.products'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.bays'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.customers'),
    ('0003', 'Catálogo y clientes', null, 'table', 'public.vehicles'),
    ('0003', 'Catálogo y clientes', null, 'func', 'app.normalize_plate'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'services_touch'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'products_touch'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'bays_touch'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'customers_touch'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'vehicles_touch'),
    ('0003', 'Catálogo y clientes', null, 'trigger', 'vehicles_normalize_plate'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.services_company_active_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.products_company_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.products_low_stock_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.bays_branch_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.customers_company_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.customers_name_trgm'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.customers_phone_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.customers_membego_unique'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.vehicles_customer_idx'),
    ('0003', 'Catálogo y clientes', null, 'index', 'public.vehicles_plate_trgm'),
    ('0004', 'Órdenes de trabajo', null, 'table', 'public.document_counters'),
    ('0004', 'Órdenes de trabajo', null, 'table', 'public.work_orders'),
    ('0004', 'Órdenes de trabajo', null, 'table', 'public.work_order_items'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.next_document_number'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.recalc_work_order_totals'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.work_order_items_changed'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.assign_order_number'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.work_order_status_timestamps'),
    ('0004', 'Órdenes de trabajo', null, 'func', 'app.bump_customer_stats'),
    ('0004', 'Órdenes de trabajo', null, 'trigger', 'work_orders_touch'),
    ('0004', 'Órdenes de trabajo', null, 'trigger', 'work_order_items_recalc'),
    ('0004', 'Órdenes de trabajo', null, 'trigger', 'work_orders_number'),
    ('0004', 'Órdenes de trabajo', null, 'trigger', 'work_orders_status_timestamps'),
    ('0004', 'Órdenes de trabajo', null, 'trigger', 'work_orders_customer_stats'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_orders_branch_status_idx'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_orders_arrival_idx'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_orders_customer_idx'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_orders_plate_trgm'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_orders_active_queue_idx'),
    ('0004', 'Órdenes de trabajo', null, 'index', 'public.work_order_items_order_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.cash_sessions'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.cash_movements'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.ncf_sequences'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.invoices'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.invoice_items'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.expenses'),
    ('0005', 'Caja, facturas y NCF', null, 'table', 'public.commissions'),
    ('0005', 'Caja, facturas y NCF', null, 'func', 'app.recalc_cash_session'),
    ('0005', 'Caja, facturas y NCF', null, 'func', 'app.cash_movements_changed'),
    ('0005', 'Caja, facturas y NCF', null, 'func', 'app.guard_closed_cash_session'),
    ('0005', 'Caja, facturas y NCF', null, 'func', 'app.allocate_ncf'),
    ('0005', 'Caja, facturas y NCF', null, 'func', 'app.assign_invoice_number'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'cash_sessions_touch'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'cash_movements_recalc'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'cash_movements_guard_closed'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'ncf_sequences_touch'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'invoices_touch'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'invoices_number'),
    ('0005', 'Caja, facturas y NCF', null, 'trigger', 'expenses_touch'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.cash_sessions_branch_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.cash_sessions_one_open_per_branch'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.cash_movements_session_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.ncf_sequences_lookup_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.invoices_ncf_unique'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.invoices_created_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.invoices_session_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.invoices_customer_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.invoice_items_invoice_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.expenses_company_date_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.commissions_profile_idx'),
    ('0005', 'Caja, facturas y NCF', null, 'index', 'public.commissions_unpaid_idx'),
    ('0006', 'Bitácora de auditoría', null, 'table', 'public.audit_logs'),
    ('0006', 'Bitácora de auditoría', null, 'func', 'app.forbid_audit_mutation'),
    ('0006', 'Bitácora de auditoría', null, 'func', 'app.stamp_audit_actor'),
    ('0006', 'Bitácora de auditoría', null, 'trigger', 'audit_logs_no_update'),
    ('0006', 'Bitácora de auditoría', null, 'trigger', 'audit_logs_stamp_actor'),
    ('0006', 'Bitácora de auditoría', null, 'index', 'public.audit_logs_company_time_idx'),
    ('0006', 'Bitácora de auditoría', null, 'index', 'public.audit_logs_entity_idx'),
    ('0006', 'Bitácora de auditoría', null, 'index', 'public.audit_logs_actor_idx'),
    ('0007', 'Políticas RLS', null, 'policy', 'companies_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'companies_update'),
    ('0007', 'Políticas RLS', null, 'policy', 'branches_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'branches_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_select_self'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_select_tenant'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_update_self'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_admin_manage'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_no_self_escalation'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_role_ceiling_update'),
    ('0007', 'Políticas RLS', null, 'policy', 'profiles_role_ceiling_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'services_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'services_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'service_prices_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'service_prices_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'products_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'products_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'bays_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'bays_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'customers_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'customers_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'vehicles_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'vehicles_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'work_orders_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'work_orders_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'work_orders_update'),
    ('0007', 'Políticas RLS', null, 'policy', 'work_order_items_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'work_order_items_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'cash_sessions_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'cash_sessions_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'cash_sessions_update'),
    ('0007', 'Políticas RLS', null, 'policy', 'cash_movements_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'cash_movements_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'ncf_sequences_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'ncf_sequences_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'invoices_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'invoices_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'invoices_annul'),
    ('0007', 'Políticas RLS', null, 'policy', 'invoice_items_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'invoice_items_insert'),
    ('0007', 'Políticas RLS', null, 'policy', 'expenses_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'expenses_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'commissions_select_own'),
    ('0007', 'Políticas RLS', null, 'policy', 'commissions_select_management'),
    ('0007', 'Políticas RLS', null, 'policy', 'commissions_write'),
    ('0007', 'Políticas RLS', null, 'policy', 'audit_logs_select'),
    ('0007', 'Políticas RLS', null, 'policy', 'audit_logs_insert'),
    ('0008', 'Cobro y facturación', null, 'func', 'app.resolve_item_price'),
    ('0008', 'Cobro y facturación', null, 'func', 'public.create_invoice'),
    ('0008', 'Cobro y facturación', null, 'func', 'public.annul_invoice'),
    ('0008', 'Cobro y facturación', null, 'column', 'public.invoices.client_request_id'),
    ('0008', 'Cobro y facturación', null, 'column', 'public.invoices.credits_invoice_id'),
    ('0008', 'Cobro y facturación', null, 'index', 'public.invoices_idempotency_unique'),
    ('0008', 'Cobro y facturación', null, 'index', 'public.invoices_credits_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'func', 'app.inherit_company_from_work_order'),
    ('0009', 'Llaves compuestas por empresa', null, 'func', 'app.inherit_company_from_invoice'),
    ('0009', 'Llaves compuestas por empresa', null, 'trigger', 'work_order_items_inherit_company'),
    ('0009', 'Llaves compuestas por empresa', null, 'trigger', 'invoice_items_inherit_company'),
    ('0009', 'Llaves compuestas por empresa', null, 'column', 'public.work_order_items.company_id'),
    ('0009', 'Llaves compuestas por empresa', null, 'column', 'public.invoice_items.company_id'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.work_order_items_company_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.invoice_items_company_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.cash_movements_invoice_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.cash_movements_expense_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.invoices_work_order_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.work_orders_bay_idx'),
    ('0009', 'Llaves compuestas por empresa', null, 'index', 'public.work_orders_vehicle_idx'),
    ('0010', 'Avance de órdenes', null, 'table', 'public.work_order_assignees'),
    ('0010', 'Avance de órdenes', null, 'func', 'app.order_transition_allowed'),
    ('0010', 'Avance de órdenes', null, 'func', 'app.enforce_order_transition'),
    ('0010', 'Avance de órdenes', null, 'func', 'public.create_work_order'),
    ('0010', 'Avance de órdenes', null, 'func', 'public.advance_work_order'),
    ('0010', 'Avance de órdenes', null, 'trigger', 'work_orders_enforce_transition'),
    ('0010', 'Avance de órdenes', null, 'policy', 'work_order_assignees_select'),
    ('0010', 'Avance de órdenes', null, 'policy', 'work_order_assignees_write'),
    ('0010', 'Avance de órdenes', null, 'column', 'public.work_orders.client_request_id'),
    ('0010', 'Avance de órdenes', null, 'index', 'public.work_orders_idempotency_unique'),
    ('0010', 'Avance de órdenes', null, 'index', 'public.work_order_assignees_profile_idx'),
    ('0011', 'Gastos y administración', null, 'table', 'public.membego_sync_logs'),
    ('0011', 'Gastos y administración', null, 'func', 'public.create_expense'),
    ('0011', 'Gastos y administración', null, 'func', 'public.dashboard_metrics'),
    ('0011', 'Gastos y administración', null, 'func', 'app.stamp_membego_actor'),
    ('0011', 'Gastos y administración', null, 'trigger', 'membego_sync_logs_no_mutation'),
    ('0011', 'Gastos y administración', null, 'trigger', 'membego_sync_logs_stamp'),
    ('0011', 'Gastos y administración', null, 'policy', 'membego_sync_logs_select'),
    ('0011', 'Gastos y administración', null, 'policy', 'membego_sync_logs_insert'),
    ('0011', 'Gastos y administración', null, 'column', 'public.expenses.client_request_id'),
    ('0011', 'Gastos y administración', null, 'index', 'public.expenses_idempotency_unique'),
    ('0011', 'Gastos y administración', null, 'index', 'public.membego_sync_logs_company_time_idx'),
    ('0012', 'Estado fiscal', null, 'func', 'public.fiscal_status'),
    ('0013', 'Alta de empleados', null, 'func', 'public.create_employee'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'table', 'public.membego_company_links'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'table', 'public.membego_webhook_events'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'table', 'public.memberships'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'table', 'public.customer_promotions'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'func', 'app.membego_company'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'func', 'public.membego_link_company'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'func', 'public.membego_ingest_event'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'trigger', 'membego_company_links_touch'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'trigger', 'memberships_touch'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'trigger', 'customer_promotions_touch'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'policy', 'membego_company_links_select'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'policy', 'memberships_select'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'policy', 'customer_promotions_select'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'index', 'public.memberships_customer_idx'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'index', 'public.memberships_company_idx'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'index', 'public.promotions_customer_idx'),
    ('0014', 'Integración Membego', 'membego_0014_0015.sql', 'index', 'public.promotions_available_idx'),
    ('0015', 'SSO de Membego', 'membego_0014_0015.sql', 'func', 'public.membego_sso_upsert_user'),
    ('0016', 'SSO saliente', 'membego_0017_sso_saliente.sql', 'func', 'public.membego_sso_saliente'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'table', 'public.inventory_movements'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'type', 'app.inventory_movement_kind'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'func', 'app.products_stock_guard'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'func', 'app.products_stock_initial'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'func', 'public.adjust_stock'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'trigger', 'products_stock_guard'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'trigger', 'products_stock_initial'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'policy', 'inventory_movements_select'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'index', 'public.inventory_movements_product_idx'),
    ('0019', 'Inventario y kardex', 'inventario_0019.sql', 'index', 'public.inventory_movements_company_time_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'table', 'public.suppliers'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'table', 'public.purchases'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'table', 'public.purchase_items'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'table', 'public.supplier_payments'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'func', 'public.register_purchase'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'func', 'public.pay_supplier'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'trigger', 'suppliers_touch'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'trigger', 'purchases_touch'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'policy', 'suppliers_select'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'policy', 'suppliers_write'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'policy', 'purchases_select'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'policy', 'purchase_items_select'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'policy', 'supplier_payments_select'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'column', 'public.inventory_movements.purchase_id'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.suppliers_company_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.purchases_company_time_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.purchases_pending_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.purchase_items_purchase_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.purchase_items_product_idx'),
    ('0020', 'Proveedores y compras', 'compras_0020.sql', 'index', 'public.supplier_payments_purchase_idx'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'table', 'public.service_recipes'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'table', 'public.service_consumptions'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'func', 'app.consume_recipes'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'func', 'public.service_recipe_cost'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'trigger', 'service_recipes_touch'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'policy', 'service_recipes_select'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'policy', 'service_recipes_write'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'policy', 'service_consumptions_select'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'column', 'public.products.stock_frac'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'index', 'public.service_recipes_service_idx'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'index', 'public.service_consumptions_order_idx'),
    ('0021', 'Recetas de insumos', 'recetas_0021.sql', 'index', 'public.service_consumptions_company_idx'),
    ('0022', 'Reportes gerenciales', 'reportes_0022.sql', 'func', 'public.management_report'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'table', 'public.vehicle_inspections'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'table', 'public.inspection_damages'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'type', 'app.inspection_stage'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'type', 'app.damage_kind'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'type', 'app.damage_severity'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'func', 'app.inspections_freeze_signed'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'func', 'app.damages_freeze_signed'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'func', 'public.sign_inspection'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'trigger', 'vehicle_inspections_touch'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'trigger', 'vehicle_inspections_freeze'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'trigger', 'inspection_damages_freeze'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'policy', 'vehicle_inspections_select'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'policy', 'vehicle_inspections_write'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'policy', 'inspection_damages_select'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'policy', 'inspection_damages_write'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'index', 'public.vehicle_inspections_order_idx'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'index', 'public.vehicle_inspections_company_idx'),
    ('0023', 'Inspección de recepción', 'inspeccion_0023.sql', 'index', 'public.inspection_damages_inspection_idx'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'table', 'public.qc_checklist_items'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'table', 'public.qc_reviews'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'table', 'public.qc_review_results'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'type', 'app.qc_result'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'func', 'public.submit_qc_review'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'func', 'public.qc_rework_index'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'trigger', 'qc_checklist_items_touch'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'policy', 'qc_checklist_items_select'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'policy', 'qc_checklist_items_write'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'policy', 'qc_reviews_select'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'policy', 'qc_review_results_select'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'index', 'public.qc_checklist_items_company_idx'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'index', 'public.qc_reviews_order_idx'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'index', 'public.qc_reviews_company_idx'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'index', 'public.qc_reviews_washer_idx'),
    ('0024', 'Control de calidad', 'calidad_0024.sql', 'index', 'public.qc_review_results_review_idx'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'table', 'public.equipment'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'table', 'public.maintenance_orders'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'type', 'app.equipment_status'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'type', 'app.maintenance_kind'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'type', 'app.maintenance_status'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'func', 'public.open_maintenance'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'func', 'public.complete_maintenance'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'trigger', 'equipment_touch'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'trigger', 'maintenance_orders_touch'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'policy', 'equipment_select'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'policy', 'equipment_write'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'policy', 'maintenance_orders_select'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'policy', 'maintenance_orders_write'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'index', 'public.equipment_company_idx'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'index', 'public.equipment_due_idx'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'index', 'public.maintenance_orders_equipment_idx'),
    ('0025', 'Mantenimiento de equipos', 'equipos_0025.sql', 'index', 'public.maintenance_orders_open_idx'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'table', 'public.appointments'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'type', 'app.appointment_status'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'func', 'app.overlapping_appointments'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'func', 'public.appointment_availability'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'func', 'public.book_appointment'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'func', 'public.convert_appointment'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'trigger', 'appointments_touch'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'policy', 'appointments_select'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'policy', 'appointments_write'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'index', 'public.appointments_branch_day_idx'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'index', 'public.appointments_company_idx'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'index', 'public.appointments_active_idx'),
    ('0026', 'Agenda y reservaciones', 'agenda_0026.sql', 'index', 'public.appointments_customer_idx'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'table', 'public.claims'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'table', 'public.claim_events'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'type', 'app.claim_kind'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'type', 'app.claim_status'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'func', 'app.claim_events_append_only'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'func', 'public.open_claim'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'func', 'public.add_claim_note'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'func', 'public.resolve_claim'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'trigger', 'claims_touch'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'trigger', 'claim_events_no_mutation'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'policy', 'claims_select'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'policy', 'claims_write'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'policy', 'claim_events_select'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'policy', 'claim_events_insert'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'index', 'public.claims_company_time_idx'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'index', 'public.claims_open_idx'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'index', 'public.claims_order_idx'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'index', 'public.claims_customer_idx'),
    ('0027', 'Reclamos e incidentes', 'reclamos_0027.sql', 'index', 'public.claim_events_claim_idx'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'table', 'public.receivables'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'table', 'public.receivable_payments'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'app.customers_credit_guard'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'app.credit_snapshot'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'public.customer_credit_status'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'public.set_customer_credit'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'app.open_receivable'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'app.cancel_receivable'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'public.collect_receivable'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'func', 'public.receivables_aging'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'trigger', 'customers_credit_guard'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'trigger', 'receivables_touch'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'policy', 'receivables_select'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'policy', 'receivable_payments_select'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'column', 'public.customers.credit_enabled'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'column', 'public.customers.credit_limit_cents'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'column', 'public.customers.credit_terms_days'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'index', 'public.customers_credit_idx'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'index', 'public.receivables_customer_idx'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'index', 'public.receivables_due_idx'),
    ('0028', 'Crédito y cuentas por cobrar', 'credito_0028.sql', 'index', 'public.receivable_payments_receivable_idx'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'table', 'public.fleets'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'table', 'public.fleet_rates'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'app.fleet_for_plate'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.upsert_fleet'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.assign_vehicle_to_fleet'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.set_fleet_rate'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.delete_fleet_rate'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.invoice_fleet_period'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'func', 'public.fleet_statement'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'trigger', 'fleets_touch'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'trigger', 'fleet_rates_touch'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'policy', 'fleets_select'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'policy', 'fleet_rates_select'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'column', 'public.vehicles.fleet_id'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'column', 'public.work_orders.fleet_id'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'column', 'public.work_orders.consolidated_invoice_id'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.fleets_company_idx'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.fleets_customer_idx'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.vehicles_fleet_idx'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.fleet_rates_specific_unique'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.fleet_rates_generic_unique'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.fleet_rates_fleet_idx'),
    ('0029', 'Flotillas y contratos', 'flotillas_0029.sql', 'index', 'public.work_orders_fleet_pending_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'table', 'public.work_shifts'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'table', 'public.attendance_records'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'table', 'public.payroll_advances'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'table', 'public.payroll_periods'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'table', 'public.payroll_items'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'type', 'app.payroll_type'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'type', 'app.payroll_status'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'app.profiles_pay_guard'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.set_employee_pay'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.schedule_shift'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.delete_shift'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.clock_in'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.clock_out'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.register_payroll_advance'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.open_payroll_period'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'app.recalc_payroll_period'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.adjust_payroll_item'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.approve_payroll'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.pay_payroll'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'func', 'public.delete_payroll_period'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'trigger', 'profiles_pay_guard'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'trigger', 'work_shifts_touch'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'trigger', 'payroll_periods_touch'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'trigger', 'payroll_items_touch'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'policy', 'work_shifts_select'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'policy', 'attendance_select'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'policy', 'payroll_advances_select'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'policy', 'payroll_periods_select'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'policy', 'payroll_items_select'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'column', 'public.profiles.payroll_type'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'column', 'public.profiles.base_salary_cents'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'column', 'public.profiles.hourly_rate_cents'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'column', 'public.commissions.payroll_item_id'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.work_shifts_profile_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.work_shifts_company_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.attendance_profile_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.attendance_company_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.attendance_one_open_per_profile'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.payroll_advances_pending_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.payroll_periods_company_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.payroll_items_period_idx'),
    ('0030', 'Turnos, asistencia y nómina', 'nomina_0030.sql', 'index', 'public.commissions_unlinked_idx'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'type', 'app.branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'func', 'app.profiles_scope_guard'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'func', 'app.can_see_branch'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'func', 'public.upsert_branch'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'func', 'public.set_employee_branch'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'trigger', 'profiles_scope_guard'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'work_orders_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'invoices_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'cash_sessions_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'expenses_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'bays_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'appointments_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'inspections_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'qc_reviews_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'equipment_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'claims_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'commissions_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'receivables_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'purchases_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'inventory_movements_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'work_shifts_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'policy', 'attendance_branch_scope'),
    ('0031', 'Multisucursal', 'sucursales_0031.sql', 'column', 'public.profiles.branch_scope'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'table', 'public.promotions'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'table', 'public.promotion_redemptions'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'type', 'app.promotion_kind'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'type', 'app.promotion_scope'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'func', 'app.promotion_discount'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'func', 'public.validate_promotion'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'func', 'public.upsert_promotion'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'func', 'app.redeem_promotion'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'trigger', 'promotions_touch'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'policy', 'promotions_select'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'policy', 'redemptions_select'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'column', 'public.companies.max_manual_discount_bps'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'index', 'public.promotions_code_unique'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'index', 'public.promotions_active_idx'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'index', 'public.redemptions_promotion_idx'),
    ('0032', 'Promociones y descuentos', 'promociones_0032.sql', 'index', 'public.redemptions_customer_idx'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'table', 'public.notifications'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'type', 'app.notification_kind'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'type', 'app.notification_audience'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'type', 'app.notification_channel'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'type', 'app.notification_status'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'func', 'app.enqueue_notification'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'func', 'app.notify_order_ready'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'func', 'public.refresh_alerts'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'func', 'public.mark_notification'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'trigger', 'notifications_touch'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'trigger', 'work_orders_notify_ready'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'policy', 'notifications_select'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'policy', 'notifications_branch_scope'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'index', 'public.notifications_pending_idx'),
    ('0033', 'Avisos y notificaciones', 'avisos_0033.sql', 'index', 'public.notifications_kind_idx'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'func', 'app.mark_item_credited'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'func', 'app.receivable_pending_for_invoice'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'func', 'app.apply_credit_to_receivable'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'func', 'public.credit_note_invoice'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'func', 'public.reset_employee_password'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'column', 'public.invoices.credited_cents'),
    ('0034', 'Notas de crédito, fiscal y usuarios', 'notas_credito_0034.sql', 'column', 'public.invoice_items.credited_quantity'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.import_text'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.phone_key'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.format_phone'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.parse_money'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.parse_int'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.parse_bool'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.slug_code'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'app.parse_vehicle_category'),
    ('0035', 'Importación masiva', 'importacion_0035.sql', 'func', 'public.import_batch')
),
-- Cada objeto se busca donde de verdad vive, no por su nombre a secas.
detectadas as (
  select e.*,
    case e.tipo
      when 'table'   then to_regclass(e.objeto) is not null
      when 'index'   then to_regclass(e.objeto) is not null
      when 'type'    then exists (
        select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace
        where n.nspname = split_part(e.objeto, '.', 1)
          and t.typname = split_part(e.objeto, '.', 2))
      when 'func'    then exists (
        select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = split_part(e.objeto, '.', 1)
          and p.proname = split_part(e.objeto, '.', 2))
      when 'trigger' then exists (
        select 1 from pg_trigger where not tgisinternal and tgname = e.objeto)
      when 'policy'  then exists (
        select 1 from pg_policies where policyname = e.objeto)
      when 'column'  then exists (
        select 1 from information_schema.columns
        where table_schema = split_part(e.objeto, '.', 1)
          and table_name   = split_part(e.objeto, '.', 2)
          and column_name  = split_part(e.objeto, '.', 3))
    end as presente
  from esperadas e
),
-- Numera lo que falta para poder nombrar solo los primeros.
ordenadas as (
  select d.*, row_number() over (partition by num, presente
                                 order by tipo, objeto) as rn
  from detectadas d
),
veredicto as (
  select num,
         min(modulo) as modulo,
         min(parche) as parche,
         count(*) filter (where presente)     as hay,
         count(*)                             as total,
         count(*) filter (where not presente) as n_faltan,
         string_agg(objeto, ', ' order by objeto)
           filter (where not presente and rn <= 5) as faltantes
  from ordenadas
  group by num
),
-- Sella lo que está completo…
sellado as (
  insert into app.schema_migrations (version, name, patch_file, detected)
  select num, modulo, parche, true from veredicto where hay = total
  on conflict (version) do nothing
  returning 1
),
-- …y le quita el sello a lo que no lo está, para que el registro no mienta.
limpieza as (
  delete from app.schema_migrations
  where version in (select num from veredicto where hay <> total)
  returning 1
)
select "Nº", "Módulo", "Estado", "Objetos", "Qué falta", "Parche a ejecutar"
from (
  -- Fila 0: el veredicto de una ojeada.
  select 0 as orden, '——' as "Nº", 'RESUMEN' as "Módulo",
    case when (select count(*) from veredicto where hay <> total) = 0
         then '✅ todo al día'
         else '❌ faltan ' || (select count(*) from veredicto where hay <> total)::text
    end as "Estado",
    (select count(*) filter (where hay = total) || ' / ' || count(*)
       from veredicto) as "Objetos",
    case when (select count(*) from veredicto where hay <> total) = 0
         then 'Las 33 migraciones están completas. No hay nada pendiente.'
         else 'Ejecute estos parches EN ESTE ORDEN, uno por uno:'
    end as "Qué falta",
    coalesce((select string_agg(coalesce(parche, '(esquema base)'), '  →  '
                                order by num)
                from veredicto where hay <> total), '') as "Parche a ejecutar"

  union all

  -- El detalle, una fila por migración.
  select 1, num, modulo,
    case when hay = total then '✅ aplicada'
         when hay = 0     then '❌ FALTA'
         else                  '⚠️ INCOMPLETA' end,
    hay || ' / ' || total,
    case when n_faltan = 0 then ''
         else faltantes || case when n_faltan > 5
                                then ' … y ' || (n_faltan - 5) || ' más'
                                else '' end
    end,
    case when hay = total then ''
         else coalesce(parche, '(esquema base — avise antes de tocar nada)') end
  from veredicto
) t
order by orden, "Nº";
